<a href="https://colab.research.google.com/github/Manasa-270/NLP-lab/blob/main/Exp_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Loading a Data set

In [ ]:
import pandas as pd
import numpy as np
import re

In [ ]:
data_in = pd.read_csv('/content/twitter4000.csv')
data_in

                                                 twitts  sentiment
0     is bored and wants to watch a movie  any sugge...          0
1              back in miami.  waiting to unboard ship           0
2     @misskpey awwww dnt dis brng bak memoriessss, ...          0
3                     ughhh i am so tired  blahhhhhhhhh          0
4     @mandagoforth me bad! It's funny though. Zacha...          0
...                                                 ...        ...
3995                                  i just graduated           1
3996          Templating works; it all has to be done            1
3997                   mommy just brought me starbucks           1
3998  @omarepps watching you on a House re-run...lov...          1
3999  Thanks for trying to make me smile I'll make y...          1

[4000 rows x 2 columns]

In [ ]:
data_in.head()

                                              twitts  sentiment
0  is bored and wants to watch a movie  any sugge...          0
1           back in miami.  waiting to unboard ship           0
2  @misskpey awwww dnt dis brng bak memoriessss, ...          0
3                  ughhh i am so tired  blahhhhhhhhh          0
4  @mandagoforth me bad! It's funny though. Zacha...          0

In [ ]:
data_in.tail()

                                                 twitts  sentiment
3995                                  i just graduated           1
3996          Templating works; it all has to be done            1
3997                   mommy just brought me starbucks           1
3998  @omarepps watching you on a House re-run...lov...          1
3999  Thanks for trying to make me smile I'll make y...          1

In [ ]:
data_in.count()

twitts       4000
sentiment    4000
dtype: int64

In [ ]:
data_in.isnull().sum()

twitts       0
sentiment    0
dtype: int64

In [ ]:
data_in.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   twitts     4000 non-null   object
 1   sentiment  4000 non-null   int64
dtypes: int64(1), object(1)
memory usage: 62.6+ KB

In [ ]:
data_in['sentiment'].value_counts()

sentiment
0    2000
1    2000
Name: count, dtype: int64

In [ ]:
pattern =r'\s'
data_in['twitts'].apply(lambda x:len(re.sub(pattern,'',x)))

0        43
1        32
2        54
3        27
4       116
       ...
3995     14
3996     32
3997     27
3998     45
3999     63
Name: twitts, Length: 4000, dtype: int64

In [ ]:
data_in

                                                 twitts  sentiment
0     is bored and wants to watch a movie  any sugge...          0
1              back in miami.  waiting to unboard ship           0
2     @misskpey awwww dnt dis brng bak memoriessss, ...          0
3                     ughhh i am so tired  blahhhhhhhhh          0
4     @mandagoforth me bad! It's funny though. Zacha...          0
...                                                 ...        ...
3995                                  i just graduated           1
3996          Templating works; it all has to be done            1
3997                   mommy just brought me starbucks           1
3998  @omarepps watching you on a House re-run...lov...          1
3999  Thanks for trying to make me smile I'll make y...          1

[4000 rows x 2 columns]

In [ ]:
data_in['char_counts'] =data_in['twitts'].apply(lambda x:len(re.sub(pattern,'',x)))

In [ ]:
data_in

,twitts,sentiment,char_counts
0,is bored and wants to watch a movie any sugge...,0,43
1,back in miami. waiting to unboard ship,0,32
2,"@misskpey awwww dnt dis brng bak memoriessss, ...",0,54
3,ughhh i am so tired blahhhhhhhhh,0,27
4,@mandagoforth me bad! It's funny though. Zacha...,0,116
...,...,...,...
3995,i just graduated,1,14
3996,Templating works; it all has to be done,1,32
3997,mommy just brought me starbucks,1,27
3998,@omarepps watching you on a House re-run...lov...,1,45
3999,Thanks for trying to make me smile I'll make y...,1,63

In [ ]:
data_in['word_counts'] = data_in['twitts'].apply(lambda x: len(x.split()))

In [ ]:
data_in.sample()

,twitts,sentiment,char_counts,word_counts
2598,Just sent my 99% revision of my NYC pitch to l...,1,70,15

In [ ]:
data_in['avg_word_length']=data_in['char_counts']/data_in['word_counts']

In [ ]:
data_in.sample(3)

,twitts,sentiment,char_counts,word_counts,avg_word_length
630,Opps.... slept tooo long,0,21,4,5.25
3671,"@freekleemhuis Face, hand, shoulders... etc, y...",1,66,10,6.60
2966,@sassyback dude I'm gen y myself,1,27,6,4.50

In [ ]:
data_in['avg_word_length'].apply(lambda x: round(x,2))

0       4.30
1       4.57
2       4.50
3       4.50
4       4.46
        ...
3995    4.67
3996    4.00
3997    5.40
3998    5.62
3999    3.94
Name: avg_word_length, Length: 4000, dtype: float64

In [ ]:
data_in.sample(3)

,twitts,sentiment,char_counts,word_counts,avg_word_length
3512,My Resident Advisor top 10: http://bit.ly/TzmY...,1,55,10,5.500
691,@ekrelly,0,8,1,8.000
3178,I have my hairs done.... I have to get used to...,1,58,16,3.625

In [ ]:
data_in['hash_tags_count'] =data_in['twitts'].apply(lambda x: len(re.findall(r'#\w+',x)))

In [ ]:
data_in.sample(3)

,twitts,sentiment,char_counts,word_counts,avg_word_length,hash_tags_count
3606,"@Virtual_Yoga, @durgamaa.....ooh, liking this ...",1,113,16,7.062500,0
2216,@behelzebub You move onto Web until it refreshes,1,41,8,5.125000,0
1457,@branli I've been in an out today. Had a long ...,0,45,13,3.461538,0

In [ ]:
data_in['mentions_count'] =data_in['twitts'].apply(lambda x: len(re.findall(r'@\w+',x)))

In [ ]:
data_in.sample(3)

,twitts,sentiment,char_counts,word_counts,avg_word_length,hash_tags_count,mentions_count
2880,"touched by the gifts received, time will put t...",1,102,24,4.250000,0,0
3436,"@glamorous_be dunno, just amazon.com :p but i ...",1,76,14,5.428571,0,1
3470,www.myspace.com/myfinalthought,1,30,1,30.000000,0,0

In [ ]:
data_in['mentions_count'].value_counts()

mentions_count
0    2153
1    1752
2      75
3      11
4       6
9       2
5       1
Name: count, dtype: int64

In [ ]:
data_in[data_in['mentions_count']>0]

,twitts,sentiment,char_counts,word_counts,avg_word_length,hash_tags_count,mentions_count
2,"@misskpey awwww dnt dis brng bak memoriessss, ...",0,54,12,4.500000,0,1
4,@mandagoforth me bad! It's funny though. Zacha...,0,116,26,4.461538,0,1
6,@kevinmarquis haha yep but i really need to sl...,0,94,22,4.272727,0,1
7,eating some ice-cream while I try to see @pete...,0,88,14,6.285714,0,1
8,@phatty84 just hella bored at work lol,0,32,7,4.571429,0,1
...,...,...,...,...,...,...,...
3989,"@imjstsayin have a good night, get your writin...",1,55,14,3.928571,0,1
3990,@LittleFletcher sounds great!!!! I hope you lo...,1,57,10,5.700000,0,1
3993,"@imstardust heyhey darling, would you be free ...",1,93,19,4.894737,0,1
3994,@saravananr @HeyCameron @thejetset thanks for ...,1,72,11,6.545455,0,3
3998,@omarepps watching you on a House re-run...lov...,1,45,8,5.625000,0,1

In [ ]:
data_in['twitts'].apply(lambda x: len([word for word in x.split() if word.isupper()]))

0       0
1       0
2       1
3       0
4       0
       ..
3995    0
3996    0
3997    0
3998    0
3999    0
Name: twitts, Length: 4000, dtype: int64

In [ ]:
data_in['upperCase_count']=data_in['twitts'].apply(lambda x: len([word for word in x.split() if word.isupper()]))

In [ ]:
data_in.sample(3)

,twitts,sentiment,char_counts,word_counts,avg_word_length,hash_tags_count,mentions_count,upperCase_count
3181,@PRPeta look forward to seeing more of Maisy a...,1,48,10,4.800000,0,1,0
2584,"@Avinio im taking her to rotschild, beach, shu...",1,92,22,4.181818,0,1,0
1546,The day I leave my car across the street all d...,0,107,30,3.566667,0,0,2

In [ ]:
data_in['twitts']

0       is bored and wants to watch a movie  any sugge...
1                back in miami.  waiting to unboard ship
2       @misskpey awwww dnt dis brng bak memoriessss, ...
3                       ughhh i am so tired  blahhhhhhhhh
4       @mandagoforth me bad! It's funny though. Zacha...
                              ...
3995                                    i just graduated
3996            Templating works; it all has to be done
3997                     mommy just brought me starbucks
3998    @omarepps watching you on a House re-run...lov...
3999    Thanks for trying to make me smile I'll make y...
Name: twitts, Length: 4000, dtype: object

In [ ]:
data_in['twitts'].apply(lambda x: re.sub(r'\s+',' ',x).lower())

0       is bored and wants to watch a movie any sugges...
1                 back in miami. waiting to unboard ship
2       @misskpey awwww dnt dis brng bak memoriessss, ...
3                        ughhh i am so tired blahhhhhhhhh
4       @mandagoforth me bad! it's funny though. zacha...
                              ...
3995                                    i just graduated
3996             templating works; it all has to be done
3997                     mommy just brought me starbucks
3998    @omarepps watching you on a house re-run...lov...
3999    thanks for trying to make me smile i'll make y...
Name: twitts, Length: 4000, dtype: object

In [ ]:
pattern = r'@\w+'
data_in['twitts'].apply(lambda x: re.sub(pattern,'',x).strip())

0       is bored and wants to watch a movie  any sugge...
1                 back in miami.  waiting to unboard ship
2       awwww dnt dis brng bak memoriessss,  I thnk I'...
3                       ughhh i am so tired  blahhhhhhhhh
4       me bad! It's funny though. Zachary Quinto is o...
                              ...
3995                                     i just graduated
3996              Templating works; it all has to be done
3997                      mommy just brought me starbucks
3998           watching you on a House re-run...lovin it.
3999    Thanks for trying to make me smile I'll make y...
Name: twitts, Length: 4000, dtype: object

In [ ]:
pattern = r'[^\w\s]'
data_in['twitts'].apply(lambda x: re.sub(pattern,'',x))

0       is bored and wants to watch a movie  any sugge...
1                 back in miami  waiting to unboard ship
2       misskpey awwww dnt dis brng bak memoriessss  I...
3                       ughhh i am so tired  blahhhhhhhhh
4       mandagoforth me bad Its funny though Zachary Q...
                              ...
3995                                    i just graduated
3996             Templating works it all has to be done
3997                     mommy just brought me starbucks
3998      omarepps watching you on a House rerunlovin it
3999    Thanks for trying to make me smile Ill make yo...
Name: twitts, Length: 4000, dtype: object

In [ ]:
pattern = r'\w+@\w+.\w+'
result = data_in['twitts'].apply(lambda x: re.findall(pattern=pattern,string=x))
result

0       []
1       []
2       []
3       []
4       []
        ..
3995    []
3996    []
3997    []
3998    []
3999    []
Name: twitts, Length: 4000, dtype: object

In [ ]:
print(result)

0       []
1       []
2       []
3       []
4       []
        ..
3995    []
3996    []
3997    []
3998    []
3999    []
Name: twitts, Length: 4000, dtype: object

In [ ]:
data_in1=pd.read_csv('/content/twitter4000.csv')

In [ ]:
pattern = r'\b[A-Za-z0-9._%+-]+@[A-ZA-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'
data_in1['email'] = data_in1['twitts'].apply(lambda x: ",".join(re.findall(pattern=pattern,string=x)))
data_in1['email_count'] = data_in1['twitts'].apply(lambda x:x.count(',')+1 if len(x)>0 else 0)

In [ ]:
data_in1.head()

,twitts,sentiment,email,email_count,email1,url,url_count
0,is bored and wants to watch a movie any sugge...,0,,1,is bored and wants to watch a movie any sugge...,[],0
1,back in miami. waiting to unboard ship,0,,1,back in miami. waiting to unboard ship,[],0
2,"@misskpey awwww dnt dis brng bak memoriessss, ...",0,,2,"@misskpey awwww dnt dis brng bak memoriessss, ...",[],0
3,ughhh i am so tired blahhhhhhhhh,0,,1,ughhh i am so tired blahhhhhhhhh,[],0
4,@mandagoforth me bad! It's funny though. Zacha...,0,,1,@mandagoforth me bad! It's funny though. Zacha...,[],0

In [ ]:
data_in1

,twitts,sentiment,email,email_count,email1,url,url_count
0,is bored and wants to watch a movie any sugge...,0,,0,is bored and wants to watch a movie any sugge...,[],0
1,back in miami. waiting to unboard ship,0,,0,back in miami. waiting to unboard ship,[],0
2,"@misskpey awwww dnt dis brng bak memoriessss, ...",0,,0,"@misskpey awwww dnt dis brng bak memoriessss, ...",[],0
3,ughhh i am so tired blahhhhhhhhh,0,,0,ughhh i am so tired blahhhhhhhhh,[],0
4,@mandagoforth me bad! It's funny though. Zacha...,0,,0,@mandagoforth me bad! It's funny though. Zacha...,[],0
...,...,...,...,...,...,...,...
3995,i just graduated,1,,0,i just graduated,[],0
3996,Templating works; it all has to be done,1,,0,Templating works; it all has to be done,[],0
3997,mommy just brought me starbucks,1,,0,mommy just brought me starbucks,[],0
3998,@omarepps watching you on a House re-run...lov...,1,,0,@omarepps watching you on a House re-run...lov...,[],0
3999,Thanks for trying to make me smile I'll make y...,1,,0,Thanks for trying to make me smile I'll make y...,[],0

In [ ]:
data_in1['email']

0       []
1       []
2       []
3       []
4       []
        ..
3995    []
3996    []
3997    []
3998    []
3999    []
Name: email, Length: 4000, dtype: object

In [ ]:
data_in1['email']

0
1
2
3
4
       ..
3995
3996
3997
3998
3999
Name: email, Length: 4000, dtype: object

In [ ]:
data_in1['email'].value_counts()

email
                               3999
markbradbury_16@hotmail.com       1
Name: count, dtype: int64

In [ ]:
data_in1['email_count']=data_in1['email'].apply(lambda x: x.count(',')+1 if len(x)>0 else 0)

In [ ]:
data_in1['email_count']

0       0
1       0
2       0
3       0
4       0
       ..
3995    0
3996    0
3997    0
3998    0
3999    0
Name: email_count, Length: 4000, dtype: int64

In [ ]:
data_in1['email1'] = data_in1['twitts'].apply(lambda x: re.sub(pattern,'',x))

In [ ]:
data_in1['email1']

0       is bored and wants to watch a movie  any sugge...
1                back in miami.  waiting to unboard ship
2       @misskpey awwww dnt dis brng bak memoriessss, ...
3                       ughhh i am so tired  blahhhhhhhhh
4       @mandagoforth me bad! It's funny though. Zacha...
                              ...
3995                                    i just graduated
3996            Templating works; it all has to be done
3997                     mommy just brought me starbucks
3998    @omarepps watching you on a House re-run...lov...
3999    Thanks for trying to make me smile I'll make y...
Name: email1, Length: 4000, dtype: object

In [ ]:
pattern = r'http\S+|www\.\S+'

In [ ]:
data_in1['url']=data_in1['twitts'].apply(lambda x: re.findall(pattern=pattern,string=x))

In [ ]:
data_in1['url']

0       []
1       []
2       []
3       []
4       []
        ..
3995    []
3996    []
3997    []
3998    []
3999    []
Name: url, Length: 4000, dtype: object

In [ ]:
data_in1['url'].value_counts()

url
[]                                                       3804
[www.tweeteradder.com]                                      2
[http://twitpic.com/4eojz]                                  1
[http://bit.ly/eId8A]                                       1
[http://blip.fm/~8lc2f]                                     1
                                                         ...
[http://tinyurl.com/kwmynq, http://plurk.com/p/yshbc]       1
[http://twitpic.com/69b67]                                  1
[www.iamsoannoyed.com]                                      1
[http://twitpic.com/7jgf1]                                  1
[http://twitpic.com/6tw87]                                  1
Name: count, Length: 196, dtype: int64

In [ ]:
data_in1['url_count'] = data_in1['url'].apply(lambda x: x.count(',')+1 if len(x)>0 else 0)

In [ ]:
data_in1[data_in1['url_count']>0]

,twitts,sentiment,email,email_count,email1,url,url_count
16,@BrianQuest I made 1 fo u 2: http://bit.ly/eId...,0,,0,@BrianQuest I made 1 fo u 2: http://bit.ly/eId...,[http://bit.ly/eId8A],1
98,Heading to work http://twitpic.com/4eojz,0,,0,Heading to work http://twitpic.com/4eojz,[http://twitpic.com/4eojz],1
99,@BlondeBlogger http://twitpic.com/4w8hk - I'm ...,0,,0,@BlondeBlogger http://twitpic.com/4w8hk - I'm ...,[http://twitpic.com/4w8hk],1
144,I miss you â« http://blip.fm/~8lc2f,0,,0,I miss you â« http://blip.fm/~8lc2f,[http://blip.fm/~8lc2f],1
183,Photo: miss germany http://tumblr.com/xf825f012,0,,0,Photo: miss germany http://tumblr.com/xf825f012,[http://tumblr.com/xf825f012],1
...,...,...,...,...,...,...,...
3826,http://tinyurl.com/kwmynq Helmet - Unsung to s...,1,,0,http://tinyurl.com/kwmynq Helmet - Unsung to s...,"[http://tinyurl.com/kwmynq, http://plurk.com/p...",1
3837,@r0ckergirl14 wow sweet again!! http://twitpi...,1,,0,@r0ckergirl14 wow sweet again!! http://twitpi...,[http://twitpic.com/69b67],1
3855,@KristineDulay why limit your story to 140 ch....,1,,0,@KristineDulay why limit your story to 140 ch....,[www.iamsoannoyed.com],1
3958,Someone has been creative with my #deskmess wh...,1,,0,Someone has been creative with my #deskmess wh...,[http://twitpic.com/7jgf1],1
3974,@gtucker13 http://twitpic.com/6tw87 - no reall...,1,,0,@gtucker13 http://twitpic.com/6tw87 - no reall...,[http://twitpic.com/6tw87],1

In [ ]:
data_in1[data_in1['url_count']>0].head()

,twitts,sentiment,email,email_count,email1,url,url_count
16,@BrianQuest I made 1 fo u 2: http://bit.ly/eId...,0,,0,@BrianQuest I made 1 fo u 2: http://bit.ly/eId...,[http://bit.ly/eId8A],1
98,Heading to work http://twitpic.com/4eojz,0,,0,Heading to work http://twitpic.com/4eojz,[http://twitpic.com/4eojz],1
99,@BlondeBlogger http://twitpic.com/4w8hk - I'm ...,0,,0,@BlondeBlogger http://twitpic.com/4w8hk - I'm ...,[http://twitpic.com/4w8hk],1
144,I miss you â« http://blip.fm/~8lc2f,0,,0,I miss you â« http://blip.fm/~8lc2f,[http://blip.fm/~8lc2f],1
183,Photo: miss germany http://tumblr.com/xf825f012,0,,0,Photo: miss germany http://tumblr.com/xf825f012,[http://tumblr.com/xf825f012],1

In [ ]:
data_in1['twitts'] = data_in1['twitts'].apply(lambda x: re.sub(pattern,'',x))

In [ ]:
data_in1[data_in1['url_count']>0].head()

,twitts,sentiment,email,email_count,email1,url,url_count
16,@BrianQuest I made 1 fo u 2: I tried but its...,0,,0,@BrianQuest I made 1 fo u 2: http://bit.ly/eId...,[http://bit.ly/eId8A],1
98,Heading to work,0,,0,Heading to work http://twitpic.com/4eojz,[http://twitpic.com/4eojz],1
99,@BlondeBlogger - I'm so sad this is so blurry!,0,,0,@BlondeBlogger http://twitpic.com/4w8hk - I'm ...,[http://twitpic.com/4w8hk],1
144,I miss you â«,0,,0,I miss you â« http://blip.fm/~8lc2f,[http://blip.fm/~8lc2f],1
183,Photo: miss germany,0,,0,Photo: miss germany http://tumblr.com/xf825f012,[http://tumblr.com/xf825f012],1

In [ ]:
import re
x ='www.google.com is the website for finding the sentence'

pattern = r'www\.+'

output = re.findall(pattern,x)
print(output)

['www.']